version: '2'

services:

  nginx:
    image: nginx
    ports:
      - 80:80
    depends_on:
      - redmine
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    restart: always

  redmine:
    image: redmine:3-passenger
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: example
    depends_on:
      - db
    restart: always

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: redmine
    restart: always
